# Generated by Django 5.0 on 2024-08-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=1000)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KafshModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('size', models.FloatField()),
                ('color', models.CharField(choices=[('blabk', 'blabk'), ('white', 'white'), ('red', 'red'), ('blue', 'blue'), ('yellow', 'yellow'), ('green', 'green'), ('pink', 'pink'), ('purple', 'purple'), ('gray', 'gray'), ('orange', 'orange')], max_length=30)),
                ('takhfif', models.CharField(choices=[('No takhfif', 'No takhfif'), ('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%')], max_length=16)),
                ('n', models.IntegerField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('sabad', models.TextField(default='[]')),
                ('macs', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kafsh1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k1', to='page.kafshmodel')),
                ('kafsh2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k2', to='page.kafshmodel')),
                ('kafsh3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k3', to='page.kafshmodel')),
                ('kafsh4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k4', to='page.kafshmodel')),
                ('kafsh5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='k5', to='page.kafshmodel')),
            ],
        ),
    ]
